MODEL_NAME = "Qwen/Qwen2.5-1.5B-Instruct"
OUTPUT_DIR = "./outputs/lora"

MAX_PROMPT_LENGTH = 256
MAX_LENGTH = 512
MAX_COMPLETION_LENGTH = 128

BETA = 0.1
LEARNING_RATE = 5e-5
BATCH_SIZE = 1
GRAD_ACCUM_STEPS = 8
EPOCHS = 2
